blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/ItsMe-RiiK/TaskBarHero-Cheetos/discussions
    about: Need help using Cheetos? Want to suggest a feature? Ask here!
