#pragma once
#include <cstdint>
#include <string>
#include <unordered_map>

enum class StatType : int32_t {
  NONE                       = 0,
  AttackDamage               = 1,
  AttackSpeed                = 2,
  CriticalChance             = 3,
  CriticalDamage             = 4,
  MaxHp                      = 5,
  Armor                      = 6,
  MovementSpeed              = 7,
  AreaOfEffect               = 8,
  BaseAttackCountReduction   = 9,
  CooldownReduction          = 10,
  SkillRangeExpansion        = 11,
  FireResistance             = 12,
  ColdResistance             = 13,
  LightningResistance        = 14,
  ChaosResistance            = 15,
  DodgeChance                = 16,
  BlockChance                = 17,
  MaxDodgeChance             = 18,
  MaxBlockChance             = 19,
  Multistrike                = 20,
  HpLeech                    = 21,
  ProjectileCount            = 22,
  HpRegenPerSec              = 23,
  PhysicalDamagePercent      = 24,
  FireDamagePercent          = 25,
  ColdDamagePercent          = 26,
  LightningDamagePercent     = 27,
  ChaosDamagePercent         = 28,
  MaxFireResistance          = 29,
  MaxColdResistance          = 30,
  MaxLightningResistance     = 31,
  MaxChaosResistance         = 32,
  AddHpPerHit                = 33,
  DamageReduction            = 34,
  PhysicalDamageReduction    = 35,
  FireDamageReduction        = 36,
  ColdDamageReduction        = 37,
  LightningDamageReduction   = 38,
  ChaosDamageReduction       = 39,
  DamageAbsorption           = 40,
  DamageAddition             = 41,
  PhysicalDamageAddition     = 42,
  FireDamageAddition         = 43,
  ColdDamageAddition         = 44,
  LightningDamageAddition    = 45,
  ChaosDamageAddition        = 46,
  IncreaseExpAmount          = 47,
  AdditionalExp              = 48,
  CastSpeed                  = 49,
  SkillHealIncrease          = 50,
  SkillDurationIncrease      = 51,
  AllElementalResistance     = 52,
  IncreaseProjectileDamage   = 53,
  IncreaseMeleeDamage        = 54,
  IncreaseAreaOfEffectDamage = 55,
  IncreaseSummonDamage       = 56,
  IncreaseProjectileSpeed    = 57,
  AddHpPerKill               = 58,
  AddAllSkillLevel           = 59,
  ElementalBlockChance       = 60,
  ElementalDodgeChance       = 61,
  MaxElementalBlockChance    = 62,
  MaxElementalDodgeChance    = 63,
};

inline const std::unordered_map<std::string, StatType>& StatNameToType()
{
  static const std::unordered_map<std::string, StatType> m = {
    {"MHP", StatType::MaxHp},
    {"DPS", StatType::AttackDamage},
    {"ATK_SPD", StatType::AttackSpeed},
    {"CRIT_CHANCE", StatType::CriticalChance},
    {"CRIT_DMG", StatType::CriticalDamage},
    {"ARMOR", StatType::Armor},
    {"MOV_SPD", StatType::MovementSpeed},
    {"CAST_SPD", StatType::CastSpeed},
    {"CDR", StatType::CooldownReduction},
  };
  return m;
}